# Generated by Django 4.1 on 2023-06-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_twinkle'),
    ]

    operations = [
        migrations.CreateModel(
            name='kitty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.TextField(max_length=50)),
            ],
        ),
    ]
